name: Deploy to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test server structure
      run: |
        python -c "
        import main
        print('✅ Server imports successfully')
        print(f'✅ Server has {len(main.mcp.list_tools())} tools')
        "
    
    - name: Test without API key (structure only)
      run: |
        python test_server.py || echo "Expected to fail without API key"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Railway
      run: |
        echo "🚀 Ready for Railway deployment"
        echo "Railway will automatically deploy from this repository"
